server:
  port: 7002

spring:
  profiles: peer2


eureka:
  instance:
    name: peer2
#    prefer-ip-address: true

  client:
    #false表示自己就是注册中心 无需检索服务
    fetch-registry: true
    #eurekaserver无需注册到eureka上
    register-with-eureka: true
    service-url:
      defaultZone:  http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/
