server:
  port: 7002

spring:
  profiles: peer2


eureka:
  server:
    my-url: http://peer2:7002/eureka/
    enable-self-preservation: true
  instance:
    hostname: peer2

  client:
    #false表示自己就是注册中心 无需检索服务
    fetch-registry: true
    #eurekaserver无需注册到eureka上
    register-with-eureka: true
    service-url:
      defaultZone:  http://peer1:7001/eureka/,http://peer2:7002/eureka/,http://peer3:7003/eureka/
